import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import { Container } from "@mui/material";
import SearchInput from "@/components/SearchInput";
import EmojiResults from "@/components/EmojiResults";
import { useState } from "react";
import filterEmojis from "@/utils/filterEmojis";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [filteredEmojis, setFilteredEmojis] = useState(filterEmojis("", 20));

  const handleChange = (searchText) => {
    setFilteredEmojis(filterEmojis(searchText, 20));
  };

  return (
    <>
      <Head>
        <title>Emoji Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Container maxWidth="sm" sx={{ bgcolor: "background.paper" }}>
          <Header />
          <SearchInput handleChange={handleChange} />
          <EmojiResults emojis={filteredEmojis} />
        </Container>
      </main>
    </>
  );
}
