import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import MyButton from "@/components/MyButton";
import MyProfile from "@/components/Profile";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const user = {
  username: "Abdou",
  avatarUrl:
    "https://www.basketusa.com/wp-content/uploads/2013/12/bird-portrait.jpg",
};

export default function Home() {
  const [isConnected, setIsConnected] = useState(false);

  function handleClick() {
    setIsConnected(!isConnected);
  }

  return (
    <>
      <Head>
        <title>Bienvenue sur React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={styles.title}>Welcome to my app</h1>
        {isConnected ? (
          <MyProfile
            username={user.username}
            avatarUrl={user.avatarUrl}
            games={user.games}
          />
        ) : (
          <p>Utilisateur non connecté</p>
        )}
        <MyButton isConnected={isConnected} handleClick={handleClick} />
      </main>
    </>
  );
}
